### ISSUE TITLE
Bug: Undefined NaN and Clicking on Home bring back to homepage

### ISSUE THREAD

**Issue by rvp-hashib** [Suchica/workstats#99]
![image](https://user-images.githubusercontent.com/92151090/182285350-4a6c7d98-a4c8-4236-a40b-78a1aada6f9e.png)
![image](https://user-images.githubusercontent.com/92151090/182285445-0f66372a-bf3c-4ef1-a21d-d4a3bf7fe76c.png)
![image](https://user-images.githubusercontent.com/92151090/182285458-b980bde5-1e01-4127-ab62-78b4bc021ed7.png)

**Comment by peeyalk** [comment]
Solved
